pipeline{
    agent{
        label 'master'
    }

    stages{
        stage('Checkout'){
            step{
                echo ""
            }
        }

        stage('Build'){
            step{
                echo ""
            }
        }

        stage('Publish'){
            step{
                echo ""
            }
        }

        stage('Deploy'){
            step{
                echo ""
            }
        }
    }
}