pipeline{
    agent{
        label 'master'
    }

    environment{
        BUILD_DIR="${WORKSPACE}/initial"
    }

    stages{
        stage('Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'GITHUB_USER', url: 'https://github.com/julianogpc/gs-spring-boot.git']]])
            }
        }

        stage('Build'){
            steps{
                dir("${BUILD_DIR}"){
                    sh '''
                        ./gradlew bootJar
                    '''
                }
            }
        }

        stage('Publish'){
            steps{
                dir("${BUILD_DIR}"){
                    sh '''
                        echo ""
                    '''
                }
            }
        }

        stage('Deploy'){
            steps{
                echo ""
            }
        }
    }
}